services:
  - type: web
    name: netflix-clone-api
    env: node
    plan: free
    region: oregon
    buildCommand: cd server && npm install --include=dev && npm run build
    startCommand: cd server && npm start
    
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: netflix_clone_super_secret_key_2026_production
      - key: JWT_EXPIRE
        value: 7d
      - key: TMDB_API_KEY
        value: 8dcba2c5d42d8060925a212e54656155
      - key: TMDB_BASE_URL
        value: https://api.themoviedb.org/3
      - key: MONGODB_URI
        fromDatabase:
          name: netflix-clone-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://netflix-clone-hh1d.vercel.app

databases:
  - name: netflix-clone-db
    plan: free
    region: oregon
    ipAllowList: []
